import { Repository } from 'typeorm';
import { IUserRepository } from '../../../domain/repositories/IUserRepository';
import { User } from '../../../domain/entities/User';
import { Email } from '../../../domain/valueObjects/Email';
import { Password } from '../../../domain/valueObjects/Password';
import { UserEntity } from './entities/UserEntity';
import { TypeOrmConnection } from './TypeOrmConnection';

export class TypeOrmUserRepository implements IUserRepository {
  private get repository(): Repository<UserEntity> {
    return TypeOrmConnection.getInstance().getDataSource().getRepository(UserEntity);
  }

  public async save(user: User): Promise<User> {
    try {
      const userEntity = new UserEntity();
      // If the user has an ID, we might want to set it, but for new users, let DB generate it.
      // However, the domain User entity might have an ID generated by the domain or passed in.
      // If the ID is not empty, we use it.
      if (user.getId()) {
        userEntity.id = user.getId();
      }

      userEntity.email = user.getEmail().getValue();
      userEntity.password = user.getPassword().getHash();
      userEntity.createdAt = user.getCreatedAt();

      const savedEntity = await this.repository.save(userEntity);

      return this.toDomain(savedEntity);
    } catch (error: unknown) {
      // Type guard for PostgreSQL error with code property
      if (
        error &&
        typeof error === 'object' &&
        'code' in error &&
        error.code === '23505'
      ) {
        throw new Error('Email already exists');
      }

      // Type guard for Error instances
      if (error instanceof Error) {
        throw new Error(`Failed to save user: ${error.message}`);
      }

      throw new Error('Failed to save user: Unknown error');
    }
  }

  public async findByEmail(email: Email): Promise<User | null> {
    const userEntity = await this.repository.findOne({
      where: { email: email.getValue() },
    });

    if (!userEntity) {
      return null;
    }

    return this.toDomain(userEntity);
  }

  public async findById(id: string): Promise<User | null> {
    const userEntity = await this.repository.findOne({
      where: { id },
    });

    if (!userEntity) {
      return null;
    }

    return this.toDomain(userEntity);
  }

  public async existsByEmail(email: Email): Promise<boolean> {
    const count = await this.repository.count({
      where: { email: email.getValue() },
    });

    return count > 0;
  }

  private toDomain(entity: UserEntity): User {
    const email = new Email(entity.email);
    const password = Password.fromHash(entity.password);

    return new User(entity.id, email, password, entity.createdAt);
  }
}
